"""Seed categories and price items."""

SEED_CATEGORIES = [
    {"code": "precious_metal", "name": "贵金属", "icon": "🥇"},
    {"code": "energy", "name": "能源", "icon": "⛽"},
    {"code": "daily_necessities", "name": "生活必需品", "icon": "🛒"},
    {"code": "commodity", "name": "大宗商品", "icon": "📦"},
    {"code": "forex", "name": "汇率", "icon": "💱"},
    {"code": "equity", "name": "股票指数", "icon": "📈"},
    {"code": "tech", "name": "科技芯片", "icon": "💾"},
]

SEED_ITEMS = [
    # 贵金属
    {
        "code": "gold_sge_au9999",
        "name": "上海金 Au99.99",
        "unit": "元/克",
        "source": "AKShare/SGE",
        "region": "全国",
        "category_code": "precious_metal",
    },
    {
        "code": "silver_sge_ag9999",
        "name": "上海银 Ag99.99",
        "unit": "元/千克",
        "source": "AKShare/SGE",
        "region": "全国",
        "category_code": "precious_metal",
    },
    {
        "code": "platinum_sge_pt9995",
        "name": "上海铂 Pt99.95",
        "unit": "元/克",
        "source": "AKShare/SGE",
        "region": "全国",
        "category_code": "precious_metal",
    },
    {
        "code": "gold_intl_usd",
        "name": "国际金价",
        "unit": "美元/盎司",
        "source": "FreeGoldAPI",
        "region": "国际",
        "category_code": "precious_metal",
    },
    # 能源
    {
        "code": "oil_wti",
        "name": "WTI 原油",
        "unit": "美元/桶",
        "source": "FRED",
        "region": "国际",
        "category_code": "energy",
    },
    {
        "code": "oil_brent",
        "name": "Brent 原油",
        "unit": "美元/桶",
        "source": "FRED",
        "region": "国际",
        "category_code": "energy",
    },
    {
        "code": "gas_henry_hub",
        "name": "Henry Hub 天然气",
        "unit": "美元/百万英热",
        "source": "FRED",
        "region": "国际",
        "category_code": "energy",
    },
    {
        "code": "oil_gasoline_national",
        "name": "国内汽油指导价",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "energy",
    },
    {
        "code": "oil_diesel_national",
        "name": "国内柴油指导价",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "energy",
    },
    {
        "code": "oil_gasoline_92",
        "name": "92#汽油",
        "unit": "元/升",
        "source": "Eastmoney/TianAPI",
        "region": "北京",
        "category_code": "energy",
    },
    {
        "code": "oil_gasoline_92_sh",
        "name": "92#汽油",
        "unit": "元/升",
        "source": "Eastmoney/TianAPI",
        "region": "上海",
        "category_code": "energy",
    },
    {
        "code": "oil_gasoline_92_gd",
        "name": "92#汽油",
        "unit": "元/升",
        "source": "Eastmoney/TianAPI",
        "region": "广东",
        "category_code": "energy",
    },
    {
        "code": "oil_gasoline_92_zj",
        "name": "92#汽油",
        "unit": "元/升",
        "source": "Eastmoney/TianAPI",
        "region": "浙江",
        "category_code": "energy",
    },
    {
        "code": "oil_gasoline_92_sc",
        "name": "92#汽油",
        "unit": "元/升",
        "source": "Eastmoney/TianAPI",
        "region": "四川",
        "category_code": "energy",
    },
    # 生活必需品
    {
        "code": "basket_index",
        "name": "菜篮子批发价格指数",
        "unit": "指数",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    {
        "code": "agri_index",
        "name": "农产品批发价格总指数",
        "unit": "指数",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    {
        "code": "pork",
        "name": "猪肉（生猪成交均价）",
        "unit": "元/公斤",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    {
        "code": "eggs",
        "name": "鸡蛋",
        "unit": "元/500千克",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    {
        "code": "sugar",
        "name": "白糖",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    # 保留旧 code，数据源已切换为可用现货
    {
        "code": "peanut_oil",
        "name": "豆油",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    {
        "code": "palm_oil",
        "name": "棕榈油",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    {
        "code": "rapeseed_oil",
        "name": "菜籽油",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    {
        "code": "soybean_meal",
        "name": "豆粕",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    {
        "code": "rice_late_indica",
        "name": "玉米（国内现货）",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "daily_necessities",
    },
    # 大宗商品
    {
        "code": "copper",
        "name": "铜（国际）",
        "unit": "美元/吨",
        "source": "FRED",
        "region": "国际",
        "category_code": "commodity",
    },
    {
        "code": "aluminum",
        "name": "铝（国际）",
        "unit": "美元/吨",
        "source": "FRED",
        "region": "国际",
        "category_code": "commodity",
    },
    {
        "code": "wheat",
        "name": "小麦",
        "unit": "美元/吨",
        "source": "FRED",
        "region": "国际",
        "category_code": "commodity",
    },
    {
        "code": "corn",
        "name": "玉米（国际）",
        "unit": "美元/吨",
        "source": "FRED",
        "region": "国际",
        "category_code": "commodity",
    },
    {
        "code": "soybean",
        "name": "大豆（国际）",
        "unit": "美元/吨",
        "source": "FRED",
        "region": "国际",
        "category_code": "commodity",
    },
    {
        "code": "palm_oil_intl",
        "name": "棕榈油（国际）",
        "unit": "美元/吨",
        "source": "FRED",
        "region": "国际",
        "category_code": "commodity",
    },
    {
        "code": "copper_cn",
        "name": "铜（国内现货）",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "commodity",
    },
    {
        "code": "aluminum_cn",
        "name": "铝（国内现货）",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "commodity",
    },
    {
        "code": "zinc_cn",
        "name": "锌（国内现货）",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "commodity",
    },
    {
        "code": "rebar",
        "name": "螺纹钢",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "commodity",
    },
    {
        "code": "iron_ore",
        "name": "铁矿石",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "commodity",
    },
    {
        "code": "cotton",
        "name": "棉花",
        "unit": "元/吨",
        "source": "AKShare",
        "region": "全国",
        "category_code": "commodity",
    },
    # 汇率
    {
        "code": "usd_cny",
        "name": "美元/人民币",
        "unit": "人民币/100美元",
        "source": "AKShare/BOC",
        "region": "全国",
        "category_code": "forex",
    },
    {
        "code": "eur_cny",
        "name": "欧元/人民币",
        "unit": "人民币/100欧元",
        "source": "AKShare/BOC",
        "region": "全国",
        "category_code": "forex",
    },
    {
        "code": "jpy_cny",
        "name": "日元/人民币",
        "unit": "人民币/100日元",
        "source": "AKShare/BOC",
        "region": "全国",
        "category_code": "forex",
    },
    {
        "code": "hkd_cny",
        "name": "港元/人民币",
        "unit": "人民币/100港元",
        "source": "AKShare/BOC",
        "region": "全国",
        "category_code": "forex",
    },
    {
        "code": "gbp_cny",
        "name": "英镑/人民币",
        "unit": "人民币/100英镑",
        "source": "AKShare/BOC",
        "region": "全国",
        "category_code": "forex",
    },
    # 股票指数
    {
        "code": "idx_shanghai",
        "name": "上证指数",
        "unit": "点",
        "source": "Sina",
        "region": "国内",
        "category_code": "equity",
    },
    {
        "code": "idx_shenzhen",
        "name": "深证成指",
        "unit": "点",
        "source": "Sina",
        "region": "国内",
        "category_code": "equity",
    },
    {
        "code": "idx_chinext",
        "name": "创业板指",
        "unit": "点",
        "source": "Sina",
        "region": "国内",
        "category_code": "equity",
    },
    {
        "code": "idx_csi300",
        "name": "沪深300",
        "unit": "点",
        "source": "Sina",
        "region": "国内",
        "category_code": "equity",
    },
    {
        "code": "idx_sse50",
        "name": "上证50",
        "unit": "点",
        "source": "Sina",
        "region": "国内",
        "category_code": "equity",
    },
    {
        "code": "idx_star50",
        "name": "科创50",
        "unit": "点",
        "source": "Sina",
        "region": "国内",
        "category_code": "equity",
    },
    {
        "code": "idx_sp500",
        "name": "标普500",
        "unit": "点",
        "source": "FRED",
        "region": "国际",
        "category_code": "equity",
    },
    {
        "code": "idx_nasdaq100",
        "name": "纳斯达克100",
        "unit": "点",
        "source": "FRED",
        "region": "国际",
        "category_code": "equity",
    },
    {
        "code": "idx_djia",
        "name": "道琼斯工业平均",
        "unit": "点",
        "source": "FRED",
        "region": "国际",
        "category_code": "equity",
    },
    # 科技芯片
    {
        "code": "idx_star_chip",
        "name": "科创芯片指数",
        "unit": "点",
        "source": "Sina",
        "region": "国内",
        "category_code": "tech",
    },
    {
        "code": "etf_soxx",
        "name": "费城半导体 ETF (SOXX)",
        "unit": "美元",
        "source": "Sina",
        "region": "国际",
        "category_code": "tech",
    },
    {
        "code": "stock_smic",
        "name": "中芯国际",
        "unit": "元",
        "source": "Sina",
        "region": "国内",
        "category_code": "tech",
    },
    {
        "code": "stock_naura",
        "name": "北方华创",
        "unit": "元",
        "source": "Sina",
        "region": "国内",
        "category_code": "tech",
    },
    {
        "code": "stock_hikvision",
        "name": "海康威视",
        "unit": "元",
        "source": "Sina",
        "region": "国内",
        "category_code": "tech",
    },
    {
        "code": "stock_nvda",
        "name": "英伟达 (NVDA)",
        "unit": "美元",
        "source": "Sina",
        "region": "国际",
        "category_code": "tech",
    },
    {
        "code": "stock_aapl",
        "name": "苹果 (AAPL)",
        "unit": "美元",
        "source": "Sina",
        "region": "国际",
        "category_code": "tech",
    },
    {
        "code": "stock_amd",
        "name": "AMD",
        "unit": "美元",
        "source": "Sina",
        "region": "国际",
        "category_code": "tech",
    },
    {
        "code": "stock_mu",
        "name": "美光 (MU / DRAM)",
        "unit": "美元",
        "source": "Sina",
        "region": "国际",
        "category_code": "tech",
    },
    {
        "code": "stock_tsm",
        "name": "台积电 (TSM)",
        "unit": "美元",
        "source": "Sina",
        "region": "国际",
        "category_code": "tech",
    },
    {
        "code": "stock_intc",
        "name": "英特尔 (INTC)",
        "unit": "美元",
        "source": "Sina",
        "region": "国际",
        "category_code": "tech",
    },
    {
        "code": "semi_ppi",
        "name": "美国半导体 PPI",
        "unit": "指数",
        "source": "FRED",
        "region": "国际",
        "category_code": "tech",
    },
    {
        "code": "semi_ip",
        "name": "美国半导体工业生产指数",
        "unit": "指数",
        "source": "FRED",
        "region": "国际",
        "category_code": "tech",
    },
]

OIL_REGION_MAP = {
    "北京": "oil_gasoline_92",
    "上海": "oil_gasoline_92_sh",
    "广东": "oil_gasoline_92_gd",
    "浙江": "oil_gasoline_92_zj",
    "四川": "oil_gasoline_92_sc",
}

# QiYouJiaGe public pages used when TIANAPI_KEY is absent
OIL_QIYOU_PAGES = {
    "oil_gasoline_92": "beijing",
    "oil_gasoline_92_sh": "shanghai",
    "oil_gasoline_92_gd": "guangdong",
    "oil_gasoline_92_zj": "zhejiang",
    "oil_gasoline_92_sc": "sichuan",
}

FRED_SERIES = {
    "oil_wti": "DCOILWTICO",
    "oil_brent": "DCOILBRENTEU",
    "gas_henry_hub": "DHHNGSP",
    "copper": "PCOPPUSDM",
    "aluminum": "PALUMUSDM",
    "wheat": "PWHEAMTUSDM",
    "corn": "PMAIZMTUSDM",
    "soybean": "PSOYBUSDM",
    "palm_oil_intl": "PSOILUSDM",
    "idx_sp500": "SP500",
    "idx_nasdaq100": "NASDAQ100",
    "idx_djia": "DJIA",
    "semi_ppi": "PCU334413334413",
    "semi_ip": "IPG3344S",
}

# Sina HQ symbols → item codes (indices / A-shares / US tech)
SINA_MARKET_SYMBOLS = {
    "s_sh000001": "idx_shanghai",
    "s_sz399001": "idx_shenzhen",
    "s_sz399006": "idx_chinext",
    "s_sh000300": "idx_csi300",
    "s_sh000016": "idx_sse50",
    "s_sh000688": "idx_star50",
    "s_sh000685": "idx_star_chip",
    "sh688981": "stock_smic",
    "sz002371": "stock_naura",
    "sz002415": "stock_hikvision",
    "gb_nvda": "stock_nvda",
    "gb_aapl": "stock_aapl",
    "gb_amd": "stock_amd",
    "gb_mu": "stock_mu",
    "gb_tsm": "stock_tsm",
    "gb_intc": "stock_intc",
    "gb_soxx": "etf_soxx",
}

BASKET_SPOT_SYMBOLS: dict[str, list[str]] = {
    "JD": ["eggs"],
    "SR": ["sugar"],
    "Y": ["peanut_oil"],
    "P": ["palm_oil"],
    "OI": ["rapeseed_oil"],
    "M": ["soybean_meal"],
    "C": ["rice_late_indica"],
}

COMMODITY_SPOT_SYMBOLS: dict[str, list[str]] = {
    "CU": ["copper_cn"],
    "AL": ["aluminum_cn"],
    "ZN": ["zinc_cn"],
    "RB": ["rebar"],
    "I": ["iron_ore"],
    "CF": ["cotton"],
}

FX_COLUMNS = {
    "usd_cny": "美元",
    "eur_cny": "欧元",
    "jpy_cny": "日元",
    "hkd_cny": "港元",
    "gbp_cny": "英镑",
}

SGE_SYMBOLS = {
    "gold_sge_au9999": "Au99.99",
    "silver_sge_ag9999": "Ag99.99",
    "platinum_sge_pt9995": "Pt99.95",
}

# Fallback prices used when live fetch is unavailable (e.g. first Vercel cold start).
SEED_DEMO_PRICES = [
    {"item_code": "gold_sge_au9999", "price": "612.50", "change_pct": "0.35"},
    {"item_code": "gold_intl_usd", "price": "2650.30", "change_pct": "0.42"},
    {"item_code": "oil_wti", "price": "78.20", "change_pct": "-1.25"},
    {"item_code": "oil_gasoline_national", "price": "7.86", "change_pct": "0.12"},
    {"item_code": "pork", "price": "24.80", "change_pct": "-0.60"},
    {"item_code": "eggs", "price": "9.45", "change_pct": "0.80"},
    {"item_code": "copper", "price": "9850.00", "change_pct": "0.55"},
    {"item_code": "copper_cn", "price": "72800.00", "change_pct": "0.30"},
    {"item_code": "usd_cny", "price": "724.56", "change_pct": "0.05"},
    {"item_code": "eur_cny", "price": "781.23", "change_pct": "-0.08"},
    {"item_code": "idx_shanghai", "price": "3285.12", "change_pct": "0.72"},
    {"item_code": "idx_nasdaq100", "price": "18234.50", "change_pct": "1.05"},
    {"item_code": "stock_nvda", "price": "128.50", "change_pct": "2.10"},
    {"item_code": "stock_amd", "price": "162.30", "change_pct": "-0.45"},
]
